spring:
  application:
    name: klage-notifications-api-e2e

  datasource:
    url: ${NAIS_DATABASE_KLAGE_NOTIFICATIONS_API_E2E_KLAGE_NOTIFICATIONS_API_E2E_JDBC_URL}
    hikari:
      maximum-pool-size: 5

  flyway:
    clean-disabled: false

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8080

NOTIFICATION_EVENTS_TOPIC: klage.klage-notification-events-e2e.v1
NOTIFICATION_INTERNAL_EVENTS_TOPIC: klage.klage-notification-internal-events-e2e.v1
NOTIFICATION_INTERNAL_CHANGE_EVENTS_TOPIC: klage.klage-notification-internal-change-events-e2e.v1
NOTIFICATION_INTERNAL_SYSTEM_EVENTS_TOPIC: klage.klage-notification-internal-system-events-e2e.v1