name: Deploy kafka topics

on:
  push:
    branches:
      - main
    paths:
      - kafka-aiven/**
      - '!kafka-aiven/README.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        topic: [klage-notification-events.v1, klage-notification-internal-events.v1, klage-notification-internal-change-events.v1, klage-notification-internal-system-events.v1]
        environment: [dev, neon, argon, e2e, prod]
        include:
          - environment: dev
            cluster: dev-gcp
          - environment: neon
            cluster: dev-gcp
          - environment: argon
            cluster: dev-gcp
          - environment: e2e
            cluster: dev-gcp
          - environment: prod
            cluster: prod-gcp
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy kafka-topic ${{ matrix.topic }} to ${{ matrix.environment }}
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: kafka-aiven/${{ matrix.topic }}/topic.yaml
          VARS: kafka-aiven/${{ matrix.topic }}/${{ matrix.environment }}-vars.yaml
          PRINT_PAYLOAD: true