name: Manual deployment to environment

# run-name kan kun referere til github og inputs kontekstene
run-name: Manual deploy of ${{(contains(fromJson('["tag", "branch"]'), github.ref_type) && !contains(fromJson('["main"]'), github.ref_name)) && github.ref_name || inputs.ref_name}} to ${{inputs.nav-environment}}

on:
  workflow_dispatch:
    inputs:
      nav-environment:
        description: 'Nav environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - neon
          - argon
          - e2e
          - prod
      ref_name:
        description: 'Image tag (matching Git tag) from previous release.'
        required: true
        type: string

jobs:
  deploy-env:
    permissions:
      contents: read
      id-token: write
    uses: navikt/klage-workflows/.github/workflows/deploy-nais-app-with-custom-checkout.yml@main
    secrets: inherit
    with:
      build-tag: ${{(contains(fromJson('["tag", "branch"]'), github.ref_type) && !contains(fromJson('["main"]'), github.ref_name)) && github.ref_name || inputs.ref_name}}
      nav-cluster: ${{inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp'}}
      nav-environment: ${{inputs.nav-environment}}