name: Manual deployment to environment
# run-name kan kun referere til github og inputs kontekstene
run-name: Manual deploy of ${{(contains(fromJson('["tag", "branch"]'), github.ref_type) && !contains(fromJson('["main"]'), github.ref_name)) && github.ref_name || inputs.ref_name}} to ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      ref_name:
        description: 'Git ref_name. branch or tag'
        required: true
        type: string
        default: 'Replace with tag or branch'

jobs:
  deploy-env:
    permissions:
      contents: read
      id-token: write
    uses: navikt/klage-workflows/.github/workflows/deploy-nais-app-with-custom-checkout.yml@main
    secrets: inherit
    with:
      build-tag: ${{(contains(fromJson('["tag", "branch"]'), github.ref_type) && !contains(fromJson('["main"]'), github.ref_name)) && github.ref_name || inputs.ref_name}}
      nav-cluster: ${{inputs.environment == 'prod' && 'prod-gcp' || 'dev-gcp'}}
      nav-environment: ${{inputs.environment}}